spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus-app?currentSchema=nexus_schema
    username: nexus-app
    password: nexus-app
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
      format_sql: true
      use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8082