services:
  # 1. Zipkin (Distributed Tracing)
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9411/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. SonarQube (Code Quality)
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/api/system/status" ]
      interval: 20s
      timeout: 10s
      retries: 5

  # 3: For SQL
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: jpm-admin
      POSTGRES_DB: jpm-wm-am-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 4. Keycloak (Authentication)
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    command: ["start-dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5


  # 5 : Redis for caching and performence
  redis:
      image: redis:latest
      container_name: redis_server
      ports:
        - "6379:6379"
      networks:
        - app-network

  # 6 : Vault service
  vault:
    image: vault:1.12.7
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_API_ADDR: "http://localhost:8200"
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8200/v1/sys/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  postgres_data:
  vault_data:
